export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
export const EDIT_EVENTS_SUCCESS = "EDIT_EVENTS_SUCCESS";
export const EDIT_EVENTS_FAILURE = "EDIT_EVENTS_FAILURE";
export const DELETE_EVENTS_SUCCESS ="DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE";
