export const VIEW_USER_PROFILE = 'VIEW_USER_PROFILE';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';
