export const FETCH_UNIFORMS = "FETCH_UNIFORMS";
export const FETCH_UNIFORMS_SUCCESS = "FETCH_UNIFORMS_SUCCESS";
export const FETCH_UNIFORMS_FAILURE = "FETCH_UNIFORMS_FAILURE";
export const EDIT_UNIFORM_SUCCESS = "EDIT_UNIFORM_SUCCESS";
export const EDIT_UNIFORM_FAILURE = "EDIT_UNIFORM_FAILURE";
export const DELETE_UNIFORM_SUCCESS ="DELETE_UNIFORM_SUCCESS";
export const DELETE_UNIFORM_FAILURE = "DELETE_UNIFORM_FAILURE";
