export const SCHOOL_UPDATE = "SCHOOL_UPDATE";
export const SCHOOL_FETCH = "SCHOOL_FETCH";
export const SCHOOL_UPDATE_SUCCESS = "SCHOOL_UPDATE_SUCCESS";
export const SCHOOL_UPDATE_FAILURE = "SCHOOL_UPDATE_FAILURE";
export const SCHOOL_FETCH_FAILURE = "SCHOOL_FETCH_FAILURE";
export const SCHOOL_FETCH_SUCCESS = "SCHOOL_FETCH_SUCCESS";
