export const FETCH_SCHOOLS = "FETCH_SCHOOLS";
export const FETCH_MORE_SCHOOLS_SUCCESS = "FETCH_MORE_SCHOOLS_SUCCESS";
export const FETCH_SCHOOLS_SUCCESS = "FETCH_SCHOOLS_SUCCESS";
export const FETCH_SCHOOLS_FAILURE = "FETCH_SCHOOLS_FAILURE";
